### ISSUE TITLE
Cannot connect to MAMP mysql

### ISSUE THREAD

**Issue by kevzettler** [infostreams/db#4]
MAMP runs mysql on port 8889 and on a non standard socket. `/Applications/MAMP/tmp/mysql/mysql.sock` instead of  `/tmp/mysql.sock`

How to specify theses values to db? 

I can connect to it using the `mysql` cli utility by creating a symlink on the socket and specifying the port

**Comment by infostreams** [comment]
Hi, thanks for your report. I added some documentation to the readme on how to do this. Please see here https://github.com/infostreams/db#additional-configuration--different-port-or-socket, and reopen if that doesn't solve your issue.

**Comment by kevzettler** [comment]
@infostreams where can I find an example config file. `.db/*/config/credentials.cnf` ?  `db init` will fail to create a config file without the custom `port` and `socket` values. So I am left to guess the other default configs. I have manually created a config but it seems that `db` and `database` are unknown values?

`mysqldump: [ERROR] unknown variable 'database=databasename`

and without them I get

`mysqldump: Got error: 1046: No database selected when selecting the database`

**Comment by kevzettler** [comment]
I think I was able to get it working but I had to manually create `.db/*/config/database` and `.db/*/dumps`

and had to read through the source to find this.
